### ISSUE TITLE
Is it possible to show the captured image once the associated face is recognized in GreetingKiosk?

### ISSUE THREAD

**Issue by Juniuz** [microsoft/Cognitive-Samples-IntelligentKiosk#10]
Hi @CarlosP-MS ,

I have been playing around the app for awhile now.  I'm wondering if is it possible to show the captured image of a person once the face recognition match the real person?  It would be nice to show the image in the Greeting Kiosk saying "Welcome back, Carlos" with an image captured on top of the text.  

I have checked the class Person from the Microsoft.ProjectOxford.Face.Contract assembly but it seems there's no Image property of the class.  Is it doable to show the image?

**Comment by malantin** [comment]
For every person there are several faces saved. Each face of Type "PersonFace" has a property UserData. The app saves the location of each photo as a string here. You could use these images and display them.

**Comment by CarlosP-MS** [comment]
Hi Juniuz,

In the ProcessCameraCapture method in the GreetingKiosk code you have access to each captured photo, allowing you to do what you want. From there you can either display that image, or crop the face to focus on the faces instead. Just realize that the ProcessCameraCapture is called in a loop, so you will need to check if the Id of the person has changed so you only update the photo the first time you see each person.

Just add an Image to your XAML view with a BitmapImage element as the source, then set the source in that BitmapImage accordingly in the code behind. If you want to show the full captured image, just do something like this:

`
yourBitmapImage.SetSourceAsync((await yourImageAnalyzer.GetImageStreamCallback()).AsRandomAccessStream()); 
`

To crop the face, you can see an example in the Mall Kiosk page (https://github.com/Microsoft/Cognitive-Samples-IntelligentKiosk/blob/master/Kiosk/Views/MallKioskPage.xaml.cs#L337), but it is essentially like this:

`
yourBitmapImage.SetSourceAsync(await Util.GetCroppedBitmapAsync(yourImageAnalyzer.GetImageStreamCallback, yourFaceRectangle);
`

Carlos

**Comment by rrvenki** [comment]
1. For people who work on the kiosk app in VB language, there is no equivalent for AsRandomAccessStream function. We have to create synchronous equivalent method.
2. When we crop the image in the rectangle & store as byte array and later assign it to image, it throws an error that height & width doesn't match. I've not found an easy way to figure the size of image before assigning to image control. Am I missing something? Some insights would help. Even C# example is ok, i shall convert to VB.

**Comment by Juniuz** [comment]
Hi @CarlosP-MS , thanks for your response.  I have tried the BitmapImage with the SetSourceAsync and it worked.  I was now able to get the image stream call back as random access stream.  I really appreciate your help.  My next challenge is how to make the image display in  80 x 80 square.  I think this should be done in XAML.
