### ISSUE TITLE
Unable to build solution

### ISSUE THREAD

**Issue by jernejk** [microsoft/Cognitive-Samples-IntelligentKiosk#101]
Hi, I would like to try this project as I was building a similar thing but in Blazor WASM (https://cognitivestudio.dev/).

I started with issues that standard .NET didn't find and restart of VS 2019 fixed that for some reason (Nuget restore and other tricks didn't work).
Then I got issues with compatibility for the platform and I remembered you need to select target x64 or x86 to fix that.
Then UWP SDK version mismatched because I only have 1903 SDK and I upgraded everything to 1903. :)

Now I have a problem I don't know how to fix and I don't even know how to diagnose it.
![image](https://user-images.githubusercontent.com/5943653/83344292-08460200-a348-11ea-94a9-7846c4c75a4a.png)

It didn't create the file, so I have no information about why it's failing.

My setup:
OS: Win 10 2004
VS: 2019 16.6 and 16.7 Preview (neither worked)
SDK: 1903 (18362)

Constrains: I don't want to install VS 2017 or old UWP SDKs because of storage constraints.

Any suggestions on how to run this?
I think this is a great project but I haven't found it on Windows Store and it seems to be quite a pain to get it up and running. It would be better if it would be an app, that can be up and running in no time. :)

**Comment by dizapico** [comment]
I haven't issues with last master commit, please, try again otherwise tell me
