### ISSUE TITLE
Anomaly Detector API Key Not Accepted

### ISSUE THREAD

**Issue by ahaw021** [microsoft/Cognitive-Samples-IntelligentKiosk#103]
Hi There

I have provisioned a anomaly detection API and entered the key however still get an error

Anomaly Detector API Test: Failed! Error message: "Response status code does not indicate success: 401 (PermissionDenied)."

![image](https://user-images.githubusercontent.com/26753809/86874416-a71e0500-c123-11ea-9307-91b59fbe87a9.png)

What are troubleshooting steps that I can take?

**Comment by SamVanhoutte** [comment]
I have the same issue.  (my api endpoint was created in WestEurope)  I waited for around 5 minutes, but still that exception;
The same happens with the Translater API

**Comment by dizapico** [comment]
Because the project has "westus2" endpoint hardcoded. Solved here https://github.com/microsoft/Cognitive-Samples-IntelligentKiosk/pull/113

**Comment by dizapico** [comment]
Now we can close this issue as solved @CarlosP-MS
