### ISSUE TITLE
Image doesn't display after adding an image in Person Groups of Face Identification Setup

### ISSUE THREAD

**Issue by Juniuz** [microsoft/Cognitive-Samples-IntelligentKiosk#11]
Hi @CarlosP-MS, I noticed that after adding an image in Person Groups (Face Identification Setup), the image doesn't appear (screen capture below).  I expect the image will show as a thumbnail after it is added.  Is this a bug? or did I miss a configuration somewhere in the app?

![personimage](https://cloud.githubusercontent.com/assets/4703222/24386014/bee98728-13c9-11e7-9602-912b69c38857.png)

**Comment by CarlosP-MS** [comment]
Sometimes we can't display the images, but that doesn't mean the model is broken (the images are still part of the model stored in the cloud by the Face APIs). 

What happens is that the Face APIs don't expose the photos that have been associated with the trained models. The kiosk attempts to display those photos by associating extra information with each face sample added during training - it saves the image URL (if it came from Bing), or the local file path (if it came from the local machine) in a field associated with each sample.

At runtime the kiosk uses that field to try to display the image when you browse through the trained model, but if the image is gone from the internet, or if Windows no longer provides access to the file in the local machine, then that look-up will fail.                                                      

In a real world scenario, applications managing models would store a copy of each sample image elsewhere during training (like a Blob storage or SQL table) and store that permanent address as reference in each face sample.

**Comment by Juniuz** [comment]
Hi @CarlosP-MS thanks for your response. I really appreciate it.  Would you know where can I find the field - image URL or the local file path, of the images that are captured?  Or should I create my own model to store a copy of the image captured?  I'm sorry if my question doesn't make sense.

**Comment by CarlosP-MS** [comment]
It is the UserData field associated with each PersonFace object added to a person during training. If you search for UserData in https://github.com/Microsoft/Cognitive-Samples-IntelligentKiosk/blob/master/Kiosk/Views/PersonDetailsPage.xaml.cs you will see locations where that field is set when faces are added to the model and when that field is consumed when faces are read from the model.
