### ISSUE TITLE
Not able to build the solution in VS 2019

### ISSUE THREAD

**Issue by Neeraj-Sr** [microsoft/Cognitive-Samples-IntelligentKiosk#124]
I just cloned the project in VS 2019 fresh install and tried building it , the build fails with following error
![image](https://user-images.githubusercontent.com/14947064/105257480-db07c780-5b55-11eb-87eb-f80c4dc1ac50.png)

**Comment by sliorbar** [comment]
I get the same issue. System namespace cannot be found

**Comment by dataNstories** [comment]
I got the same issue. Any way to get around this?

**Comment by dataNstories** [comment]
I was able to resolved the 'System' build errors by 'Unload' & 'Reload' all 3 projects.    The demo is working great.  Thank you.
