### ISSUE TITLE
Translator Text API Test: Failed

### ISSUE THREAD

**Issue by ericjay1** [microsoft/Cognitive-Samples-IntelligentKiosk#126]
Tracing the request to Azure shows the Translator Text API Test does not contain a valid location . Would appreciate an explanation on how to add location to Translator Text API Test.

**Comment by AlbertDavletov** [comment]
We've added a region parameter to the Translator Text API.
PR #128

**Comment by ericjay1** [comment]
Works OK now, thanks for the fix
