### ISSUE TITLE
Cannot build - 'ComputerVisionErrorException' does not exist any more in .Net SDK

### ISSUE THREAD

**Issue by cbezenco** [microsoft/Cognitive-Samples-IntelligentKiosk#127]
I tried to build the Kiosk using the process described in the Readme but build is failing with following error

Error	CS0246	
The type or namespace name 'ComputerVisionErrorException' could not be found (are you missing a using directive or an assembly reference?)	
Project : ServiceHelpers	C:\Github\Cognitive-Samples-IntelligentKiosk\Kiosk\ServiceHelpers\VisionServiceHelper.cs	
Line : Active

After searching it looks like 'ComputerVisionErrorException' is now longer in the .Net SDK and it seems to be called ComputerVisionErrorResponseException.  now. 

I have done a few changes renaming this exception in utils.c and  but I am not sure that what I did is correct so I am not submitting a pull request as I think Kiosk dev needs to look into this. 

 var visionException = ex as Microsoft.Azure.CognitiveServices.Vision.ComputerVision.Models.ComputerVisionErrorResponseException;
            if (visionException?.Body != null)
            {
                errorDetails = visionException.Body.ToString();
            }

**Comment by AlbertDavletov** [comment]
Computer Vision package updated to the latest version. 
PR #128
