### ISSUE TITLE
Is there any way to install this directly 

### ISSUE THREAD

**Issue by abhinav-TB** [microsoft/Cognitive-Samples-IntelligentKiosk#138]

**Comment by abhinav-TB** [comment]
The windows store is asking for a code to radeem

**Comment by AlbertDavletov** [comment]
The built-in Intelligent Kiosk app is no longer available in the Store. Please use the Intelligent Kiosk sample on GitHub.
You will find the steps on how to download the code and build/deploy the app on your machine in the [Readme](https://github.com/microsoft/Cognitive-Samples-IntelligentKiosk#readme) page.
