### ISSUE TITLE
error regarding starting the camera

### ISSUE THREAD

**Issue by ap185304** [microsoft/Cognitive-Samples-IntelligentKiosk#14]
its giving error like;
requested window runtime types "windows.media.capture.mediacapture" is not registered..
so how to register that.. pls solve this issue as soon as possible

**Comment by CarlosP-MS** [comment]
What kind of platform are you trying to run the sample on? The error could be an indication that either the platform doesn't support that type (and web cams in general), or that something is wrong with your machine. If this is a regular Windows machine, try launching the built-in Camera app in Windows, for example, to see what happens.

**Comment by ap185304** [comment]
on windows 10.ok..i will try

**Comment by Jirapong** [comment]
You might want to try to install https://www.microsoft.com/en-us/download/details.aspx?id=48231 this. It solved my problem.
