### ISSUE TITLE
missing API keys for insurance claim automationg

### ISSUE THREAD

**Issue by ericjay1** [microsoft/Cognitive-Samples-IntelligentKiosk#141]
All keys on the settings page are passed, but the program tells the contrary

Face API Test: Passed!
Computer Vision API Test: Passed!
Custom Vision Training API Test: Passed!
Bing Search API Test: Passed!
Text Analytics API Test: Passed!
Translator Text API Test: Passed!
Anomaly Detector API Test: Passed!
Speech API Test: Passed!
Form Recognizer API Test: Passed!

![image](https://user-images.githubusercontent.com/78159775/124660885-19e0ce00-dea7-11eb-9a16-bbc29772e4f1.png)

**Comment by CarlosP-MS** [comment]
This demo requires you to build your own Custom Vision and Form Recognizer models, and then reference them in the code behind for the demo. More details at https://github.com/microsoft/Cognitive-Samples-IntelligentKiosk/blob/master/Documentation/InsuranceClaimAutomation.md.
