### ISSUE TITLE
Re-opening Request for Windows Store Availability 

### ISSUE THREAD

**Issue by evogelpohl** [microsoft/Cognitive-Samples-IntelligentKiosk#142]
Saw Issue #138. 

I work for a Microsoft Partner. B/c I have access to the app, I _personally_ can demo Cognitive Services with potential clients. 

Alas, my Sales/Pre-Sales teams can't. Asking them to install VS & compile a github project is a bridge too far.

I've sold many PowerApp/No-Code & ML projects based on this app. It's an *outstanding* ideation sample app. Every time I demo it w/ potential clients, they admit they had no awareness or context to how Cog Services could improve workflows & productivity apps.

I humbly ask you to reconsider your decision to remove this from the Win Store. (yes, yes, perhaps a cross platform solution?). 

Eric Vogelpohl
https://www.linkedin.com/in/ericvogelpohl/

**Comment by CarlosP-MS** [comment]
An option for folks who want to facilitate that type of consumption is to build the app locally from the GitHub code and then share the package with colleagues to install.
