### ISSUE TITLE
Failure of "Realtime Video Insights"

### ISSUE THREAD

**Issue by Traceur70** [microsoft/Cognitive-Samples-IntelligentKiosk#145]
The demo of "Realtime Video Insights" did not work because class 'FrameRelayVideoEffect' was not in a specific project of type "Windows Runtime Component" (see https://docs.microsoft.com/en-us/answers/questions/591175/how-do-i-fix-the-34class-not-registered34-error-us.html)

Please check PR #144

**Comment by CarlosP-MS** [comment]
The solution was originally this way, but a previous PR incorrectly removed the Windows Runtime Component. That PR has been reverted and now it should work. Thanks for bringing this up.
