### ISSUE TITLE
Executable won't run after build

### ISSUE THREAD

**Issue by ccjamie** [microsoft/Cognitive-Samples-IntelligentKiosk#148]
![kioskerror](https://user-images.githubusercontent.com/89472648/153022657-28319e54-0877-4c93-8a5b-69d68beecd6c.png)
Hi, on running the kiosk in visual studio using F5 it opens and is fully usable, however when trying to build, the project builds successfully but running the executable manually nothing opens and upon viewing the event viewer I found a FileNotFound Exception (screenshot attached).
Any help on this would be greatly appreciated, thanks in advance.

**Comment by CarlosP-MS** [comment]
How are you trying to launch the app? Is it via the Start Menu in Windows (search for kiosk to find it)? If it is by going to the output folder and launching the executable, that might be the reason it is failing when launched that way.

**Comment by ccjamie** [comment]
I was trying to run from the executable file, it works from the start menu, thank you.
