### ISSUE TITLE
App not accepting subscription keys

### ISSUE THREAD

**Issue by briannoyes** [microsoft/Cognitive-Samples-IntelligentKiosk#15]
I have diligently and carefully copied all the API keys from my account at:
https://azure.microsoft.com/en-us/try/cognitive-services/my-apis/

I am able to do emotion detection, but any of the demos involving facial recognition fail with errors, probably stemming from the same that results below when trying to do the Face Identification Setup:
![image](https://cloud.githubusercontent.com/assets/4534445/26287175/ae866a3c-3e43-11e7-922f-2485e56e850d.png)

**Comment by rrvenki** [comment]
One possible reason is your workspace key which is required to download your groups is not in memory. The samples use Roaming profile folder to store the keys in encrypted form. If your current user id cannot read or write to roaming folder you'll get this error. Go through SettingsHelper.vb file where Application.Current.Roaming... Code is in function LoadRoamingSettings. This will be called from App.xaml.vb. Good luck.

**Comment by CarlosP-MS** [comment]
Hi @briannoyes - are your keys by any chance provisioned against a region different than West US? If so, that is the problem (and would explain why Face and Vision, that are now multi-region, don't work, while Emotion still works). The kiosk sample currently assumes West US keys. It will soon get an update to allow you to specify the correct region associated with the keys via a drop down menu in the Settings page.

**Comment by rrvenki** [comment]
Hi @carlosP-MS. If other region are going to be supported do you also have plans with private cloud? One of my client wants my vision app to use only when the cognitive API would run in his own infrastructure (already had MS private cloud). Sorry if you want this to be separate thread, i shall move it.

**Comment by CarlosP-MS** [comment]
The update that adds multi-region support is now in. You can now define the Azure region for the Face and Computer Vision keys via a dropdown menu in the Settings page. @rrvenki, at this point just the Azure end-points are supported, but if in the future we expand support for private clouds a similar approach would enable it (e.g. provide a custom endpoint for the APIs).

**Comment by briannoyes** [comment]
@CarlosP-MS I was in fact provisioned against East US 2 region for some (since it was a choice in the drop downs in Azure) and a few that only had West US. I had also tried with keys obtained from the cognitive services home page, which didn't have region selection as I recall. Have a couple other talks at DEVintersection today but will try again with latest bits as soon as I get a chance.

Another question: in the Computer Vision session at Build 2017, the version of the kiosk Anna Roth was showing had a bunch of other choices in the Demos page - are those available anywhere?

**Comment by CarlosP-MS** [comment]
@briannoyes - yes, the boxed version of the kiosk is available at https://www.microsoft.com/store/apps/9nblggh5qd84.
