### ISSUE TITLE
Face detection failed

### ISSUE THREAD

**Issue by Malith1994124** [microsoft/Cognitive-Samples-IntelligentKiosk#16]
![image](https://user-images.githubusercontent.com/18634794/26897368-f2d93886-4be5-11e7-9d3a-e6dd7d6f5fda.png)

I have download code from here and purchase keys from azure cognitive service under South Asia region but in kiosk demos only face detection is not working and emotion sample working. Can i know the reason for this???

**Comment by CarlosP-MS** [comment]
In the Settings page in the kiosk, try setting the region for the Face API key to match your region and see if that helps. By default the kiosk (and Face SDK) assumes the key is from the West US region.

**Comment by Malith1994124** [comment]
where i can change the region??
![image](https://user-images.githubusercontent.com/18634794/26985637-0c9854a0-4d62-11e7-8e03-a7f2bc551112.png)

**Comment by CarlosP-MS** [comment]
Try syncing to the latest version of the code. That support was added a few weeks back. It will show up as a drop down menu to the right of the Face API Key and Vision API Key text boxes.

Unless you are using the IoT sample of the kiosk, as that particular change is not there yet.

**Comment by Malith1994124** [comment]
oky.
Thanks, now it working. CarlosP-MS thanks for your help

**Comment by hamidyaseen** [comment]
HI Carlos,  I am also getting the same issue as 
{  "error": {
    "code": "Unspecified",
    "message": "Access denied due to invalid subscription key. Make sure you are subscribed to an API you are trying to call and provide the right key."
  }
}
I am located in Denmark and have generated keys for Face API along with others related APIs and in the Intelligent Kiosk App setting, I have entered keys and selected Azure Zone like West Europ.. .but still the issue is same. Any help would be appreciated.
