### ISSUE TITLE
Persistent face id does not work if InteligentKiosk runs on multiple device

### ISSUE THREAD

**Issue by blrchen** [microsoft/Cognitive-Samples-IntelligentKiosk#2]
Trying to run IntelligentKiosk on multiple devices at the same time. In the real time page, only one device can get persistent face id. (Other api calls like emotion, face are all okay)

**Comment by CarlosP-MS** [comment]
Hi blrchen,

Do you mean that each device gets a different Face Id? The way the demo works at the moment, to get multiple devices to get the same Face Id for the same face, you will need to have both of them use the same Face API Key and Workspace Key, as those control which Face List gets used to store the faces while the demo is running. 

With that said, notice that with the current implementation of the realtime demo, that Face List gets reset when the demo starts/closes as well as every hour, so if you want to have multiple devices consuming the same Face List for a longer period of time, or not resetting the list when the demo starts/stops in any of the devices, then you might want to change that behavior.

Hope this helps,
Carlos
