### ISSUE TITLE
Unable to run the solution

### ISSUE THREAD

**Issue by ravik12KPIT** [microsoft/Cognitive-Samples-IntelligentKiosk#20]
Hi I've cloned the solution and followed the all steps as mentioned in document, but unfortunately no luck to see the demos, it has got stuck at the home screen which is showing a Intelligent Kiosk Sample title with windows logo, please help to resolve this issue.
![capture](https://user-images.githubusercontent.com/26485078/28623582-0c8c74c2-7234-11e7-8557-d908c54a18b3.PNG)

**Comment by CarlosP-MS** [comment]
It looks like the app is hanging during start up. I haven't seen that one before. I would run it under the debugger and once it gets into that state pause the process and look at what all threads are doing. That will hopefully lead you to the problem. The Parallel Stack Trace feature in Visual Studio is great for this, allowing you to see all threads at once and get an overall picture.
