### ISSUE TITLE
Fall Creators Upadate issue

### ISSUE THREAD

**Issue by miyamam** [microsoft/Cognitive-Samples-IntelligentKiosk#22]
Hi, I'm using this UWP compiled with VS2015 on Windows 10 FCU.
Some of feature causes suddenly application crush. Though I didn't install VS2015 on Windows 10 FCU, I couldn't debug and find any reason of this.
If we could compile current source on VS2017 and the latest NuGet library, I could compile and find these issue.

**Comment by miyamam** [comment]
Updated. When I use VS2017 on Windows 10 FCU, the issue has still happened.

**Comment by CarlosP-MS** [comment]
Can you try again? A pull request was just integrated yesterday that migrated the solutions to VS2017 and Win 10 FCU.

**Comment by miyamam** [comment]
I'm testing. As a first look, it works better.
