### ISSUE TITLE
An unhandled win 32 exception occured in IntelligentKioskSample.exe

### ISSUE THREAD

**Issue by rameeztariq** [microsoft/Cognitive-Samples-IntelligentKiosk#23]
Whenever, I try to save image from Face Identification Setup it takes me back to App.gi.cs file. What should I do? Please advice.

**Comment by CarlosP-MS** [comment]
It is a bit unclear what exactly you are trying to do, but it is likely that you are hitting an unhandled exception somewhere. If you tell Visual Studio to stop on unhandled Common Language Runtime Exceptions (look for it in the Exception Settings), it should stop earlier and hopefully help you see where the error is.
