### ISSUE TITLE
I am unable to open SettingsPage.xaml

### ISSUE THREAD

**Issue by abhijith862** [microsoft/Cognitive-Samples-IntelligentKiosk#28]
I am unable to open SettingsPage.xaml, every time I try to open the same in VS 2017 it take a lot of time and then throws an Error as "An Unhandled Exception has occurred" 

The Details of the error is stated as: "System.NullReferenceException: Object reference not set to an instance of an object.
at IntelligentKioskSample.Controls.PageHeader.<.ctor>b__0_0(Object s, RoutedEventArgs a)"

**Comment by CarlosP-MS** [comment]
That is a strange error. It should load fine. I would try closing all source code files, cleaning and rebuilding the solution before opening that page again. Sometimes the XAML designer fails to parse and render the views when the binaries are stale.

**Comment by easyj2j** [comment]
See issue #42
