### ISSUE TITLE
Capture data to a database

### ISSUE THREAD

**Issue by syedaqibm** [microsoft/Cognitive-Samples-IntelligentKiosk#3]
Hi,
How can i capture data from the app to database, like the age and emotions into a database.
Thanks

**Comment by CarlosP-MS** [comment]
Hi syedaqibm,

The exact process would depend on the type of database solution, but the general idea would be to take the results from each analyzed image and send it to that database. For example, in the Automatic Photo Capture or the Realtime Crow Insights experiences in the kiosk, the ProcessCameraCapture method would be a good entry point where you would have the data about age and emotion for each captured image.

Carlos

**Comment by syedaqibm** [comment]
Thanks alot

**Comment by blrchen** [comment]
I have done some code work by updating the Realtime page by add a TelemetryLoop task which will upload captured image to storage and send face telemetry info to event hub. Once the message is in event hub, you can easily to use Azure Stream Analytics to persistent face telemetry data to a supported database like SQL Database or Document DB.
