### ISSUE TITLE
Video Frame Flickers

### ISSUE THREAD

**Issue by matousrokos** [microsoft/Cognitive-Samples-IntelligentKiosk#30]
Hi, I've tried to deploy it on Raspberry PI3 with Windows 10 IoT core and USB attached web cam. Problem is that live video frame in top right corner flickers a lot and it's impossible to identify faces. I thought that the cam might be producing higher resolution video that PI is capable of handling without graphics acceleration so I've tried to lower resolution in CameraControl.xaml.cs. Flickering improves but not entirely. Is there something I can do?

**Comment by CarlosP-MS** [comment]
Are you already using the trimmed down version of the kiosk sample that is tailored to Raspberry PI3 and the Sense HAT? That version does tweak the camera resolution to a low setting and sizes the camera preview in the UI to a small size to reduce the load in the system. 

If that is already what you are doing, it might be compatibility issues with the web camera that you are using. The document at https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/hardwarecompatlist has the list of all compatible devices. Then for good measure I would also look for Windows updates in case there are updates that might take care of the flicker.

**Comment by matousrokos** [comment]
Hi, yes, I'm using the optimized version for PI3. My camera is not on the list however I had different experience across OS versions: In 16299 it uses some generic Microsoft driver. In in Insider builds it's get recognized but the it still flickers a little (less then 16299). In 17083 there were some general issues with video performance so I waited for 17110 where flickering is minimal but still present

**Comment by CarlosP-MS** [comment]
Sounds good. Closing for now, but if there is anything in the code that you find later that could help with this please feel free to share.
