### ISSUE TITLE
How to make this work with a remote camera?

### ISSUE THREAD

**Issue by chanchal777** [microsoft/Cognitive-Samples-IntelligentKiosk#31]
How can we make this work with a non-usb lan or IP based camera?

**Comment by CarlosP-MS** [comment]
If you look at a kiosk demo such as Face API Explorer, you will notice that you can score images from Bing image search results, local files or local web cam captures. All those three cases use the ImageAnalyzer class in the kiosk to analyze the data. You would follow the same pattern for remote cameras. If you can get images from the camera (in URL format or a byte array), then you should be able to pass that data to the ImageAnalyzer class and have it do the work for you.
