### ISSUE TITLE
How to connect with IP Camera

### ISSUE THREAD

**Issue by lequanghoan** [microsoft/Cognitive-Samples-IntelligentKiosk#33]
Dear Mr Carlos,

I am newbie on this. I studying about your sample code, then i want to replace webcam from your code to an IP Camera, but i don't know how to do. Could you give me some advices or codes

**Comment by CarlosP-MS** [comment]
Please see https://github.com/Microsoft/Cognitive-Samples-IntelligentKiosk/issues/31
