### ISSUE TITLE
Broken reference to Microsoft.ProjectOxford.Face in ServiceHelpers project

### ISSUE THREAD

**Issue by richardspitz** [microsoft/Cognitive-Samples-IntelligentKiosk#34]
Workaround: Delete current reference and add a new reference in ServiceHelpers project from: Cognitive-Samples-IntelligentKiosk\Kiosk\packages\Microsoft.ProjectOxford.Face.1.3.0\lib\portable-net45+wp80+win8+wpa81+aspnetcore50\Microsoft.ProjectOxford.Face.dll

![image](https://user-images.githubusercontent.com/15606759/40574827-164ae43c-60f7-11e8-9d48-40744ccac19f.png)

**Comment by techolutionFR** [comment]
Another alternative is uninstall/reinstall the library from NuGet. Stick with version 1.3 though.

**Comment by CarlosP-MS** [comment]
Just fixed it.
