### ISSUE TITLE
How to live stream camera output

### ISSUE THREAD

**Issue by Malith1994124** [microsoft/Cognitive-Samples-IntelligentKiosk#36]
I'm try build online learning platform using cognitive services where teacher will let know student is listening,  his emotion or he /she distracted using cognitive apis. For that i need to stream student live feed. Can you provide sample solution for it using kiosk. This is same as driving thing but i need min 3 users live feed into one lecture.

**Comment by lmiroslaw** [comment]
Why don't you try out the Wowza or other open source streaming servers?

**Comment by CarlosP-MS** [comment]
If this is about creating an experience that takes as input the live stream from multiple remote cameras (one per student), then see #31. 

If not, and this is about creating a dashboard that takes as input the insights from an app that is handling each student, then you just need to use the data in the process loop in a demo such as the driving demo to stream it to your dashboard of choice.
