### ISSUE TITLE
Build failed in visual studio

### ISSUE THREAD

**Issue by jaskarannagi19** [microsoft/Cognitive-Samples-IntelligentKiosk#37]
Hey

I already did update-package -reinstall but still facing these red issues. Attaching screenshot somebody help me out
![untitled](https://user-images.githubusercontent.com/39240649/41458863-6ee520cc-70a5-11e8-962c-122ee1d8bd75.png)

**Comment by jaskarannagi19** [comment]
![image](https://user-images.githubusercontent.com/39240649/41459513-6c6faff4-70a7-11e8-8f90-a39d9bf19b5f.png)

**Comment by CarlosP-MS** [comment]
Just fixed it.
