### ISSUE TITLE
Cannot build newly downloaded solution

### ISSUE THREAD

**Issue by terrylyons** [microsoft/Cognitive-Samples-IntelligentKiosk#39]
I have failed completely to build this project. Starting with visual studio 2017 enterprise, I downloaded the repo with VS and had recursion box checked. Then opened solution.  Tried to build the solution and then the project. Always the same errors (attached below). Tried Update-Package -reinstall and this changed versions of various components but did not fix the problems. I need to fix this - hope someone can see how. Thanks

[compile-log.txt](https://github.com/Microsoft/Cognitive-Samples-IntelligentKiosk/files/2130306/compile-log.txt)

**Comment by CarlosP-MS** [comment]
Just fixed it.
