### ISSUE TITLE
cameraControl goes off the screen

### ISSUE THREAD

**Issue by terrylyons** [microsoft/Cognitive-Samples-IntelligentKiosk#40]
If I resize a UWP from full screen when looking the emotion page, the cameraControl can drift off the visible window on the image so it becomes impossible to use it to take an image for analysis. 

It is fine for some resizing but then reaches a threshold where it follows the image and disappears off the side. Looks to me as if the control should be on the mask and not the image.

I am too new to fix it but would be interested to learn how it should be fixed.

**Comment by CarlosP-MS** [comment]
Can you provide a screenshot for reference?

**Comment by CarlosP-MS** [comment]
There is a planned work item that will improve the overal camera input control. Closing for now, as we also didn't get a repro.
