### ISSUE TITLE
Latest source code?

### ISSUE THREAD

**Issue by InsomniumBR** [microsoft/Cognitive-Samples-IntelligentKiosk#41]
Is there any repository where we can get the latest source code version of this app that is distributed through Windows Store?

App Link: https://www.microsoft.com/en-us/p/intelligent-kiosk/9nblggh5qd84?SilentAuth=1&wa=wsignin1.0

Thanks

**Comment by CarlosP-MS** [comment]
What is available now is what is in here, but see #18 for more info and feel free to comment on the particular scenario(s) you are looking for.

**Comment by InsomniumBR** [comment]
Hello @CarlosP-MS, first thanks for your quickly reply!
I work on the largest Microsoft Partner company in Brazil (Brasoftware) and it would be great to have the code behind the "Draw 3D Mesh" on the Social Photo Booth -> Realtime Face Effects demo.
I think that you will never have this as an API, so it shouldn't be a problem to share that with our community. What you think?

**Comment by CarlosP-MS** [comment]
That is not something that is available for sharing unfortunately. The closest you can get to it is the set of face landmarks that is exposed by the Face APIs. You can see those in action in the Face API Explorer demo in the kiosk.

**Comment by dalton5** [comment]
Can you please add the source code for social photobooth please?
