### ISSUE TITLE
Provide option to upload VB.NET equivalent of Intelligent Kiosk

### ISSUE THREAD

**Issue by rrvenki** [microsoft/Cognitive-Samples-IntelligentKiosk#48]
There are other community maintained VB.NET versions of the C# samples in github. Ex: ML.NET samples which are in C# and F# are maintained by "Nukepayload2/machinelearning-samples" for VB.NET.

Will it be possible to have a similar option for IntelligentKiosk so we could upload the equivalent VB.NET code?

Request you to group the "Code" by language and help us upload the working VB code under "B#".

**Comment by CarlosP-MS** [comment]
Thanks for the suggestion, but unfortunately that is not something in scope at this point.
