### ISSUE TITLE
Microsoft.ProjectOxford.Face Version

### ISSUE THREAD

**Issue by memory125** [microsoft/Cognitive-Samples-IntelligentKiosk#50]
I checked this sample, the Microsoft.ProjectOxford.Face version is 1.4.0. But I didn't find it on [Nuget](https://www.nuget.org/packages?q=Microsoft.ProjectOxford.Face). Is there any other ways to install it.

**Comment by memory125** [comment]
Here is the dependencies this sample used.
   "Microsoft.ProjectOxford.Face": "1.4.0",
    "Microsoft.ProjectOxford.Vision": "1.0.393",
    "Microsoft.Rest.ClientRuntime": "2.3.11",

**Comment by nnmer** [comment]
> I checked this sample, the Microsoft.ProjectOxford.Face version is 1.4.0. But I didn't find it on [Nuget](https://www.nuget.org/packages?q=Microsoft.ProjectOxford.Face). Is there any other ways to install it.

@memory125 Set the specific version, in your case it is a 1.4.0, in your packages.config or your project's csproj file PackageReference section and try to restore packages. It should download the 1.4.0 version for you

**Comment by memory125** [comment]
> > I checked this sample, the Microsoft.ProjectOxford.Face version is 1.4.0. But I didn't find it on [Nuget](https://www.nuget.org/packages?q=Microsoft.ProjectOxford.Face). Is there any other ways to install it.
> 
> @memory125 Set the specific version, in your case it is a 1.4.0, in your packages.config or your project's csproj file PackageReference section and try to restore packages. It should download the 1.4.0 version for you

One more question, as the project.json file specified, we can set the specific version for dependent libs, but when something went wrong, we need to upgrade the dependent lib version to the latest or rollback to the previous version, how to know the specific version number?

**Comment by nnmer** [comment]
from the docs:

[Nuget Deleting packages](https://docs.microsoft.com/en-us/nuget/policies/deleting-packages)

> nuget.org does not support permanent deletion of packages. ............
nuget.org does supports unlisting a package, ..... . Unlisted packages don't appear on nuget.org or in the Visual Studio UI, and do not appear in search results. Unlisted packages, however, can still be downloaded and installed by using an exact version number, which supports package restore. 


Unlisting is the deleting meaning, but with backward compatibility. That means that the package will **not** have future versions. Thus, you need to consider to replace the dependent package

**Comment by memory125** [comment]
> from the docs:
> 
> [Nuget Deleting packages](https://docs.microsoft.com/en-us/nuget/policies/deleting-packages)
> 
> > nuget.org does not support permanent deletion of packages. ............
> > nuget.org does supports unlisting a package, ..... . Unlisted packages don't appear on nuget.org or in the Visual Studio UI, and do not appear in search results. Unlisted packages, however, can still be downloaded and installed by using an exact version number, which supports package restore.
> 
> Unlisting is the deleting meaning, but with backward compatibility. That means that the package will **not** have future versions. Thus, you need to consider to replace the dependent package

Thanks

**Comment by CarlosP-MS** [comment]
We have just migrated to the latest SDKs

**Comment by ajaykeshri** [comment]
In Nuget  "Microsoft.ProjectOxford.Vision" has only version 1.1.0, But this version not able to install in     
 NETStandard-2, In my project I am using NETStandard version 2. How can i access this library for OCR scan.
