### ISSUE TITLE
Image Collection Insights Some Photo Index out Bound 

### ISSUE THREAD

**Issue by Vallenteer** [microsoft/Cognitive-Samples-IntelligentKiosk#51]
I had some problem with some photo in my folder, every time the photo get error "Index was outside the bounds of the array. | Error picking the target folder." this happen when I used a specific photo in a folder. I want to know what cause of that? and possibly how to make sure that do not happen or just skip the photo. Because when it happen all process are halt.

for testing, one of the photo I tried and failed is this one
[DSC04188.zip](https://github.com/Microsoft/Cognitive-Samples-IntelligentKiosk/files/2772577/DSC04188.zip)

**Comment by CarlosP-MS** [comment]
Thanks for reporting the issue and uploading the image that causes it. It is a bug and the fix will be added soon.
