### ISSUE TITLE
Is it possible to run this sample on a Raspberry PI?

### ISSUE THREAD

**Issue by piffarettig** [microsoft/Cognitive-Samples-IntelligentKiosk#6]
I want to run this on a Raspberry Pi 3 that has installed Windows IoT Core. Is that possible?

In case yes, how? I ve been experiencing some troubles deploying it to the ARM (it asks me for a Windows Phone or an emulator) and then fails.

Thanks in advance!

**Comment by CarlosP-MS** [comment]
Yes, it is possible to run it on a Raspberry PI. I have done it myself. I just had to enter the IP address of the device, set the proper architecture and everything else just worked. 

The only other thing I did, but just to increase performance, was to tweak the UI code very slightly so the camera preview wasn't set to take a large portion of the screen. You can do that by adjusting the XAML for the view you will be using so the size of the control that hosts the camera preview is set to something small. And if you don't need to display any UI to a screen (e.g. you are communicating via LED lights, sound, etc) you can even go a step further and pair down the XAML to the point where you have just a thumbnail view of the camera and nothing else (e.g. no real-time charts or overlays over the camera preview).

Hope that helps!

Carlos

**Comment by piffarettig** [comment]
Thanks, I was finally able to run it on the RPI. In case this concerns to anyone in the future, what I followed was:

If, with Remote Machine selected in Visual Studio 2015 target dropdown, you are having trouble, please try:
 

- Restarting the Iot device and redeploying the app
- Restarting the dev machine and redeploying the app
- In Visual Studio, set Tools > Options > Projects and Solutions > Build and Run > MSBuild project * verbosity = Diagnostic, redeploy the app, send me the output from the Output pane.

And yes, the performance with the original app was very poor, as video playback performance on the Raspberry Pi platform is not optimized.  Animated user elements including XAML-based dropdown menus may exhibit less than optimal performance. The MinnowBoard (x86/x64) and QualComm DragonBoard (ARM) have much better perf.

What you suggest could be a great workaround though!

Thanks again!
