### ISSUE TITLE
Emotion Detection failed | Realtime Crowd Insight

### ISSUE THREAD

**Issue by rahuldutta227** [microsoft/Cognitive-Samples-IntelligentKiosk#66]
![image](https://user-images.githubusercontent.com/23102880/53426118-64ff9200-3a0c-11e9-9897-3d2eb5d37999.png)

I'm getting the "Access Denied Error" on the Realtime Crowd Insight use case.

Also below is the error log from Visual Studio:
Error detected! Exception: "Exception of type 'Microsoft.ProjectOxford.Common.ClientException' was thrown.", More info: "Emotion API RecognizeAsync error".
Exception thrown: 'Microsoft.ProjectOxford.Common.ClientException' in System.Private.CoreLib.ni.dll
Exception thrown: 'Microsoft.ProjectOxford.Common.ClientException' in System.Private.CoreLib.ni.dll
Exception thrown: 'Microsoft.ProjectOxford.Common.ClientException' in System.Private.CoreLib.ni.dll
Exception thrown: 'Microsoft.ProjectOxford.Common.ClientException' in System.Private.CoreLib.ni.dll
Error detected! Exception: "Exception of type 'Microsoft.ProjectOxford.Common.ClientException' was thrown.", More info: "Emotion API RecognizeAsync error".
The program '[948] IntelligentKioskSample.exe: Program Trace' has exited with code 0 (0x0).
The program '[948] IntelligentKioskSample.exe' has exited with code -1 (0xffffffff).

**Comment by CarlosP-MS** [comment]
It looks like you are using a very old version of the code. Could you sync to the latest version? We no longer use the Emotion APIs. Also check that the APUI Keys in the Settings Page are valid. There should be a button there to help test them out.

**Comment by rahuldutta227** [comment]
Thanks Carlos! Bang On!!!! It works after using the latest codebase.
