### ISSUE TITLE
Where could I find the FaceId value

### ISSUE THREAD

**Issue by onepelaez** [microsoft/Cognitive-Samples-IntelligentKiosk#69]
In the Realtime Crowd Insight screen, every time the app recognizes a face, a rectangular shape appears in the face showing: Gender, Age, Emotion and FaceId. This FaceId is a alphanumeric value of 4 digits (like 65d1, b901, c56d). 

So, I would like to know where can I find this value (FaceId) in the app code, I've tried with the UniqueId in the Visitor class but its returns a very long value of 20 characters. Maybe Its have to seem something with System.Guid but I'm not sure. Please can you help me, if anyone needs more info about this, let me know.. Appreciated!!

**Comment by CarlosP-MS** [comment]
Here is the line that draws that element in the UI: https://github.com/Microsoft/Cognitive-Samples-IntelligentKiosk/blob/5ce54aa7afac0419ba461bff4978ef15297788d9/Kiosk/Controls/RealTimeFaceIdentificationBorder.xaml.cs#L79

Yes, it is simply a truncated version of the long unique face id Guid.
