### ISSUE TITLE
New Cognitive Services API Endpoints

### ISSUE THREAD

**Issue by arafato** [microsoft/Cognitive-Samples-IntelligentKiosk#7]
Hi--, 

will this app be updated to use the new endoints for Face, Emotion and Vision? Currently, the app is using
api.projectoxford.ai which is not recommened to use anymore (see [https://www.microsoft.com/cognitive-services/en-US/subscriptions?mode=NewTrials](https://www.microsoft.com/cognitive-services/en-US/subscriptions?mode=NewTrials))

Thanks!

**Comment by CarlosP-MS** [comment]
Could you please point to an example? I don't remember the Face/Emotion/Vision end points being used in the code - rather it uses the SDKs, which in turn make the http requests.

**Comment by arafato** [comment]
@CarlosP-MS: It seems that the old SDKs are still being used as in [https://github.com/Microsoft/Cognitive-Samples-IntelligentKiosk/blob/master/Kiosk/ServiceHelpers/FaceServiceHelper.cs#L34](https://github.com/Microsoft/Cognitive-Samples-IntelligentKiosk/blob/master/Kiosk/ServiceHelpers/FaceServiceHelper.cs#L34)

which in turn uses the old endpoints:

[https://github.com/Microsoft/ProjectOxford-ClientSDK/blob/master/Face/Windows/ClientLibrary/FaceServiceClient.cs#L60](https://github.com/Microsoft/ProjectOxford-ClientSDK/blob/master/Face/Windows/ClientLibrary/FaceServiceClient.cs#L60)

Will that be fixed? Thanks!

**Comment by CarlosP-MS** [comment]
Yes, the Face SDK team is aware of the old end point in the Face SDK and is working on updating it. Once that is fixed we will update the NuGet reference in the kiosk sample so it points to the latest package and correct end-point. 

I just migrated the sample to the latest NuGet packages, which makes at least Emotion and Vision point to the correct end-points, but I will keep the issue open until Face is also addressed.

**Comment by CarlosP-MS** [comment]
A new Face SDK was just released that points to the new API end-point, and that reference is now used in the sample.
