### ISSUE TITLE
Unable to build the solution

### ISSUE THREAD

**Issue by shubham0490** [microsoft/Cognitive-Samples-IntelligentKiosk#71]
Hi there, I'm getting these errors while building the project, kindly help.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0518	Predefined type 'System.String' is not defined or imported	KioskRuntimeComponent	C:\WINDOWS\TEMP\.NETCore,Version=v5.0.AssemblyAttributes.cs	4	Active
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	34	Active
Error	CS0518	Predefined type 'System.Object' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	43	Active
Error	CS0012	The type 'IReadOnlyList<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	43	Active
Error	CS0518	Predefined type 'System.Object' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	45	Active
Error	CS0518	Predefined type 'System.Void' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	45	Active
Error	CS0518	Predefined type 'System.Boolean' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	47	Active
Error	CS0518	Predefined type 'System.Boolean' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	49	Active
Error	CS0246	The type or namespace name 'IReadOnlyList<>' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	55	Active
Error	CS0518	Predefined type 'System.Object' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	55	Active
Error	CS0518	Predefined type 'System.Object' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	55	Active
Error	CS0012	The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	63	Active
Error	CS0518	Predefined type 'System.Object' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	63	Active
Error	CS0012	The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	65	Active
Error	CS0518	Predefined type 'System.Boolean' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	71	Active
Error	CS0518	Predefined type 'System.Boolean' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	73	Active
Error	CS0518	Predefined type 'System.Void' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	79	Active
Error	CS0518	Predefined type 'System.Void' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	79	Active
Error	CS0012	The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	79	Active
Error	CS0518	Predefined type 'System.Object' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	79	Active
Error	CS0518	Predefined type 'System.Void' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	83	Active
Error	CS0518	Predefined type 'System.Void' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	83	Active
Error	CS0518	Predefined type 'System.Void' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	88	Active
Error	CS0518	Predefined type 'System.Void' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	93	Active
Error	CS0518	Predefined type 'System.Void' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	93	Active
Error	CS0518	Predefined type 'System.Object' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	93	Active
Error	CS0518	Predefined type 'System.Void' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	98	Active
Error	CS0518	Predefined type 'System.Void' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	98	Active
Error	CS0518	Predefined type 'System.Object' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	98	Active
Error	CS0518	Predefined type 'System.Object' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	98	Active
Error	CS0518	Predefined type 'System.Void' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	102	Active
Error	CS0518	Predefined type 'System.Void' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	102	Active
Error	CS0518	Predefined type 'System.Object' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\FrameRelayVideoEffect.cs	102	Active
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	34	Active
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	35	Active
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	36	Active
Error	CS0246	The type or namespace name 'AssemblyTitleAttribute' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	41	Active
Error	CS0246	The type or namespace name 'AssemblyTitle' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	41	Active
Error	CS0518	Predefined type 'System.String' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	41	Active
Error	CS0246	The type or namespace name 'AssemblyDescriptionAttribute' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	42	Active
Error	CS0246	The type or namespace name 'AssemblyDescription' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	42	Active
Error	CS0518	Predefined type 'System.String' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	42	Active
Error	CS0246	The type or namespace name 'AssemblyConfigurationAttribute' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	43	Active
Error	CS0246	The type or namespace name 'AssemblyConfiguration' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	43	Active
Error	CS0518	Predefined type 'System.String' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	43	Active
Error	CS0246	The type or namespace name 'AssemblyCompanyAttribute' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	44	Active
Error	CS0246	The type or namespace name 'AssemblyCompany' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	44	Active
Error	CS0518	Predefined type 'System.String' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	44	Active
Error	CS0246	The type or namespace name 'AssemblyProductAttribute' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	45	Active
Error	CS0246	The type or namespace name 'AssemblyProduct' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	45	Active
Error	CS0518	Predefined type 'System.String' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	45	Active
Error	CS0246	The type or namespace name 'AssemblyCopyrightAttribute' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	46	Active
Error	CS0246	The type or namespace name 'AssemblyCopyright' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	46	Active
Error	CS0518	Predefined type 'System.String' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	46	Active
Error	CS0246	The type or namespace name 'AssemblyTrademarkAttribute' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	47	Active
Error	CS0246	The type or namespace name 'AssemblyTrademark' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	47	Active
Error	CS0518	Predefined type 'System.String' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	47	Active
Error	CS0246	The type or namespace name 'AssemblyCultureAttribute' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	48	Active
Error	CS0246	The type or namespace name 'AssemblyCulture' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	48	Active
Error	CS0518	Predefined type 'System.String' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	48	Active
Error	CS0246	The type or namespace name 'AssemblyVersionAttribute' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	60	Active
Error	CS0246	The type or namespace name 'AssemblyVersion' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	60	Active
Error	CS0518	Predefined type 'System.String' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	60	Active
Error	CS0246	The type or namespace name 'AssemblyFileVersionAttribute' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	61	Active
Error	CS0246	The type or namespace name 'AssemblyFileVersion' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	61	Active
Error	CS0518	Predefined type 'System.String' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	61	Active
Error	CS0246	The type or namespace name 'ComVisibleAttribute' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	62	Active
Error	CS0246	The type or namespace name 'ComVisible' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	62	Active
Error	CS0518	Predefined type 'System.Boolean' is not defined or imported	KioskRuntimeComponent	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\Properties\AssemblyInfo.cs	62	Active
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\WINDOWS\TEMP\.NETCore,Version=v5.0.AssemblyAttributes.cs	2	Active
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\WINDOWS\TEMP\.NETCore,Version=v5.0.AssemblyAttributes.cs	3	Active
Error	CS0400	The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?)	KioskRuntimeComponent	C:\WINDOWS\TEMP\.NETCore,Version=v5.0.AssemblyAttributes.cs	4	Active
Error	CS0246	The type or namespace name 'FrameworkDisplayName' could not be found (are you missing a using directive or an assembly reference?)	KioskRuntimeComponent	C:\WINDOWS\TEMP\.NETCore,Version=v5.0.AssemblyAttributes.cs	4	Active
Error	CS0518	Predefined type 'System.String' is not defined or imported	KioskRuntimeComponent	C:\WINDOWS\TEMP\.NETCore,Version=v5.0.AssemblyAttributes.cs	4	Active
Error	CS2001	Source file 'C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\obj\x86\Debug\App.g.i.cs' could not be found.	IntelligentKioskSample	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\CSC	1	Active
Error		Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.'	IntelligentKioskSample	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\IntelligentKioskSample.csproj		
Error		Cannot resolve Assembly or Windows Metadata file 'C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\KioskRuntimeComponent\bin\Debug\KioskRuntimeComponent.winmd'	IntelligentKioskSample	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\IntelligentKioskSample.csproj		
Warning	NU1605	Detected package downgrade: Microsoft.Rest.ClientRuntime from 2.3.17 to 2.3.11. Reference the package directly from the project to select a different version. 
 IntelligentKioskSample -> ServiceHelpers -> Microsoft.Azure.CognitiveServices.Language.TextAnalytics 2.8.0-preview -> Microsoft.Rest.ClientRuntime (>= 2.3.17 && < 3.0.0) 
 IntelligentKioskSample -> Microsoft.Rest.ClientRuntime (>= 2.3.11)	IntelligentKioskSample	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\IntelligentKioskSample.csproj	1	
Warning	NU1605	Detected package downgrade: Microsoft.Rest.ClientRuntime from 2.3.17 to 2.3.11. Reference the package directly from the project to select a different version. 
 IntelligentKioskSample -> Microsoft.Azure.CognitiveServices.Vision.CustomVision.Training 0.13.0-preview -> Microsoft.Rest.ClientRuntime (>= 2.3.17 && < 3.0.0) 
 IntelligentKioskSample -> Microsoft.Rest.ClientRuntime (>= 2.3.11)	IntelligentKioskSample	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\IntelligentKioskSample.csproj	1	
Warning	NU1605	Detected package downgrade: Microsoft.Rest.ClientRuntime from 2.3.12 to 2.3.11. Reference the package directly from the project to select a different version. 
 IntelligentKioskSample -> Microsoft.Azure.CognitiveServices.Vision.Face 2.2.0-preview -> Microsoft.Rest.ClientRuntime (>= 2.3.12 && < 3.0.0) 
 IntelligentKioskSample -> Microsoft.Rest.ClientRuntime (>= 2.3.11)	IntelligentKioskSample	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\IntelligentKioskSample.csproj	1	
Warning	NU1605	Detected package downgrade: Microsoft.Rest.ClientRuntime from 2.3.17 to 2.3.11. Reference the package directly from the project to select a different version. 
 IntelligentKioskSample -> Microsoft.Azure.CognitiveServices.Vision.CustomVision.Prediction 0.12.0-preview -> Microsoft.Rest.ClientRuntime (>= 2.3.17 && < 3.0.0) 
 IntelligentKioskSample -> Microsoft.Rest.ClientRuntime (>= 2.3.11)	IntelligentKioskSample	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\IntelligentKioskSample.csproj	1	
Warning	NU1605	Detected package downgrade: Microsoft.Rest.ClientRuntime from 2.3.18 to 2.3.11. Reference the package directly from the project to select a different version. 
 IntelligentKioskSample -> Microsoft.Azure.CognitiveServices.Vision.ComputerVision 3.3.0 -> Microsoft.Rest.ClientRuntime (>= 2.3.18 && < 3.0.0) 
 IntelligentKioskSample -> Microsoft.Rest.ClientRuntime (>= 2.3.11)	IntelligentKioskSample	C:\Users\Shubham\source\repos\Cognitive-Samples-IntelligentKiosk-master\Kiosk\IntelligentKioskSample.csproj	1

**Comment by CarlosP-MS** [comment]
It looks like there are missing dependencies. Can you restore all NuGet packages and try again? Also please check that you have the right environment (Visual Studio and Windows version). If it still fails please re-activate.

**Comment by MichaelKMorrison** [comment]
Running... 
  Visual Studio 2017, version 15.9.2
  Windows OS 10, Build 18362
I'm having some issues too, but only 10 :) 
![image](https://user-images.githubusercontent.com/15235626/58361185-b79cee80-7e41-11e9-9348-b901657db5ec.png)
