### ISSUE TITLE
Unable to deploy the solution 

### ISSUE THREAD

**Issue by benzadeh** [microsoft/Cognitive-Samples-IntelligentKiosk#76]
I have tried cleaning the build and restoring NuGet packages without any luck. Still getting 14 errors. 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 4: cannot convert from 'string[]' to 'System.Collections.Generic.IList<System.Guid>'	IntelligentKioskSample	C:\github\Cognitive-Samples-IntelligentKiosk-master\Kiosk\Views\CustomVision\CustomVisionExplorer.xaml.cs	334	Active
Error	CS1061	'ICustomVisionPredictionClient' does not contain a definition for 'PredictImageUrlAsync' and no accessible extension method 'PredictImageUrlAsync' accepting a first argument of type 'ICustomVisionPredictionClient' could be found (are you missing a using directive or an assembly reference?)	IntelligentKioskSample	C:\github\Cognitive-Samples-IntelligentKiosk-master\Kiosk\Views\CustomVision\CustomVisionServiceHelper.cs	87	Active
Error	CS1061	'ICustomVisionPredictionClient' does not contain a definition for 'PredictImageAsync' and no accessible extension method 'PredictImageAsync' accepting a first argument of type 'ICustomVisionPredictionClient' could be found (are you missing a using directive or an assembly reference?)	IntelligentKioskSample	C:\github\Cognitive-Samples-IntelligentKiosk-master\Kiosk\Views\CustomVision\CustomVisionServiceHelper.cs	92	Active
Error	CS1503	Argument 4: cannot convert from 'string[]' to 'System.Collections.Generic.IList<System.Guid>'	IntelligentKioskSample	C:\github\Cognitive-Samples-IntelligentKiosk-master\Kiosk\Views\CustomVision\CustomVisionSetup.xaml.cs	422	Active
Error	CS1503	Argument 4: cannot convert from 'string[]' to 'System.Collections.Generic.IList<System.Guid>'	IntelligentKioskSample	C:\github\Cognitive-Samples-IntelligentKiosk-master\Kiosk\Views\CustomVision\CustomVisionSetup.xaml.cs	475	Active
Error	CS1503	Argument 3: cannot convert from 'string[]' to 'System.Collections.Generic.IList<System.Guid>'	IntelligentKioskSample	C:\github\Cognitive-Samples-IntelligentKiosk-master\Kiosk\Views\CustomVision\CustomVisionSetup.xaml.cs	525	Active
Error	CS1503	Argument 3: cannot convert from 'string[]' to 'System.Collections.Generic.IList<System.Guid>'	IntelligentKioskSample	C:\github\Cognitive-Samples-IntelligentKiosk-master\Kiosk\Views\CustomVision\CustomVisionSetup.xaml.cs	601	Active
Error	CS1503	Argument 3: cannot convert from 'string[]' to 'System.Collections.Generic.IList<System.Guid>'	IntelligentKioskSample	C:\github\Cognitive-Samples-IntelligentKiosk-master\Kiosk\Views\CustomVision\CustomVisionSetup.xaml.cs	624	Active
Error	CS1503	Argument 2: cannot convert from 'string' to 'double'	IntelligentKioskSample	C:\github\Cognitive-Samples-IntelligentKiosk-master\Kiosk\Views\CustomVision\ImageWithRegionEditorsControl.xaml.cs	196	Active
Error	CS1503	Argument 3: cannot convert from 'System.DateTime' to 'double'	IntelligentKioskSample	C:\github\Cognitive-Samples-IntelligentKiosk-master\Kiosk\Views\CustomVision\ImageWithRegionEditorsControl.xaml.cs	197	Active
Error	CS1503	Argument 4: cannot convert from 'System.Guid' to 'double'	IntelligentKioskSample	C:\github\Cognitive-Samples-IntelligentKiosk-master\Kiosk\Views\CustomVision\ImageWithRegionEditorsControl.xaml.cs	198	Active
Error	CS1503	Argument 6: cannot convert from 'double' to 'System.Guid'	IntelligentKioskSample	C:\github\Cognitive-Samples-IntelligentKiosk-master\Kiosk\Views\CustomVision\ImageWithRegionEditorsControl.xaml.cs	200	Active
Error	CS1503	Argument 7: cannot convert from 'double' to 'string'	IntelligentKioskSample	C:\github\Cognitive-Samples-IntelligentKiosk-master\Kiosk\Views\CustomVision\ImageWithRegionEditorsControl.xaml.cs	201	Active
Error	CS1503	Argument 8: cannot convert from 'double' to 'System.DateTime'	IntelligentKioskSample	C:\github\Cognitive-Samples-IntelligentKiosk-master\Kiosk\Views\CustomVision\ImageWithRegionEditorsControl.xaml.cs	202	Active

**Comment by CarlosP-MS** [comment]
All these errors are related to Custom Vision. Did you by any chance updated the NuGet packages to the latest versions in your machine? If so that is the problem, the current version of the code is not compatible with the latest SDK for Custom Vision. Try rolling back to the original version from the repo to see if it works.

We will be updating to the latest SDK soon, which should make this go away, but it might be a few weeks.
