### ISSUE TITLE
This project doesn't build under VS2017

### ISSUE THREAD

**Issue by tlandgrave** [microsoft/Cognitive-Samples-IntelligentKiosk#8]
Has anyone been able to get this to build on VS2017?

**Comment by CarlosP-MS** [comment]
I haven't tested it in VS2017, but sounds like it needs updates. At a minimum I would try a round of updating all NuGet package references to see if that helps. I will update back when I have a chance to try this out in the future.

**Comment by martenlindblad** [comment]
Build the KioskRuntimeComponent and ServiceHelpers before running the IntelligentKioskSample.
