### ISSUE TITLE
IntelligentKioskSample executable doesn't run as stand alone application

### ISSUE THREAD

**Issue by Juniuz** [microsoft/Cognitive-Samples-IntelligentKiosk#9]
Hi,

I tried to run IntelligentKioskSample.exe under /bin/x86/debug folder but to no avail I got the following error message (screen capture below)

![intelligentkiosk](https://cloud.githubusercontent.com/assets/4703222/24174604/5e1eb17a-0ef6-11e7-92a4-4a93b17ea05e.JPG)

How do I run or deploy this application?  Sorry for this newbie question, I just started to learn Microsoft UWP.

**Comment by malantin** [comment]
You should open the Solution in Visual Studio and do "Build" -> "Deploy". You could also just hit Debug to install and run on your local machine.

**Comment by Juniuz** [comment]
@n01d Thanks for your suggestion.  I already did that and the app works fine.  I just need to deploy the application not in my local machine; in other machine that runs on Windows 10 without Visual Studio.  Would copying IntelligentKioskSample.exe and run on another machine suffice?

**Comment by malantin** [comment]
Copying the exe won't work. Check out the documentation on packaging: https://docs.microsoft.com/en-us/windows/uwp/packaging/  You can create the deployment package with VS: https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps#sideload-your-app-package

**Comment by Juniuz** [comment]
@n01d thanks for sharing the link.  I have followed on how to create a deployment package and execute the Add-AppDevPackage powershell script in my target machine and it installed the intelligent kiosk sample app successfully.  This issue is now closed.
