### ISSUE TITLE
Unable to build the solution

### ISSUE THREAD

**Issue by JoergLehmann23** [microsoft/Cognitive-Samples-IntelligentKiosk#93]
I run the latest Windows 10 Version 1909 (Build 18363.476) with the latest Visual Studio 19 (Version 16.3.9). I updated all the Nuget Package for the latest versions. 

The main issue is in the ServiceHelpers and I get these build errors:

Error	CS0006	Metadata file 'C:\IntelligentKiosk\Kiosk\ServiceHelpers\bin\Release\ServiceHelpers.dll' could not be found	IntelligentKioskSample	C:\IntelligentKiosk\Kiosk\CSC	1	Active

Error	CS1739	The best overload for 'SentimentAsync' does not have a parameter named 'multiLanguageBatchInput'	ServiceHelpers	C:\IntelligentKiosk\Kiosk\ServiceHelpers\TextAnalyticsHelper.cs	117	Active

Error	CS1739	The best overload for 'KeyPhrasesAsync' does not have a parameter named 'multiLanguageBatchInput'	ServiceHelpers	C:\IntelligentKiosk\Kiosk\ServiceHelpers\TextAnalyticsHelper.cs	141	Active

Error	CS1739	The best overload for 'SentimentAsync' does not have a parameter named 'multiLanguageBatchInput'	IntelligentKioskSample	C:\IntelligentKiosk\Kiosk\CognitiveServiceApiKeyTester.cs	119	Active

Thanks for checking!

**Comment by JoergLehmann23** [comment]
I found the issue here: If I **don't** install the NuGet Package for Microsoft.Azure.CognitiveServices.Language.TextAnalytics, the solution will build.

**Comment by nhutcmos** [comment]
Same issue, I changed Microsoft.Azure.CognitiveServices.Language.TextAnalytics version 4.0.0->3.0.0 from ServiceHelpers project, then this project can build. But IntelligentKioskSample got a ton of errors

**Comment by dnkh** [comment]
Replace 
SentimentAsync with SentimentBatchAsync
KeyPhrasesAsync with KeyPhrasesBatchAsync

if you want to use Microsoft.Azure.CognitiveServices.Language.TextAnalytics version 4.0.0

**Comment by CarlosP-MS** [comment]
Text Analytics NuGet package updated to the latest version.
