### ISSUE TITLE
Custom Vision Training API Test: Failed! Error message: "Operation returned an invalid status code 'Unauthorized'. The error message was "Access Denied"."

### ISSUE THREAD

**Issue by Vallenteer** [microsoft/Cognitive-Samples-IntelligentKiosk#98]
I using my own key  & from this example
![image](https://user-images.githubusercontent.com/10533785/74752998-13e25100-52a2-11ea-83f3-5749bc08753c.png)

but keep getting API Failed, it is because the Endpoint was not complete only use 

> https://region-name.api.cognitive.microsoft.com/ 

not the custom endpoint like path in the picture?

**Comment by CarlosP-MS** [comment]
In the case of this sample, yes, as it is using an old version of the Custom Vision SDK. That is why this sample also has a selector in the settings page for the available regions, so it doesn't have to be entered manually.
